version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
      time: "07:00"
      timezone: "Europe/Paris"
    commit-message:
      prefix: "chore: "
  - package-ecosystem: pub
    directory: /app
    schedule:
      interval: daily
      time: "07:00"
      timezone: "Europe/Paris"
    commit-message:
      prefix: "chore: "