include: package:jagis_lints/analysis_options.yaml
dart_code_metrics:
  rules:
    - avoid-unnecessary-futures:
        exclude:
          - test/features/step/*.dart
    - avoid-unused-parameters:
        exclude:
          - test/features/step/*.dart
