targets:
  $default:
    builders:
      bdd_widget_test|featureBuilder:
        options:
          addHooks: true
          hookFolderName: features/bdd_hooks
        generate_for:
          include:
            - "test/features/**.feature"