const environmentalPerformanceEmptyData = {
  'liens_bilans_thematique': [
    {
      'id_enchainement_kyc': 'ENCHAINEMENT_KYC_bilan_transport',
      'image_url': 'https://res.cloudinary.com/dq023imd8/image/upload/v1728466903/Mobilite_df75aefd09.svg',
      'nombre_total_question': 9,
      'pourcentage_progression': 0,
      'temps_minutes': 5,
      'thematique': 'transport',
    },
    {
      'id_enchainement_kyc': 'ENCHAINEMENT_KYC_bilan_alimentation',
      'image_url': 'https://res.cloudinary.com/dq023imd8/image/upload/v1728466523/cuisine_da54797693.svg',
      'nombre_total_question': 6,
      'pourcentage_progression': 0,
      'temps_minutes': 3,
      'thematique': 'alimentation',
    },
    {
      'id_enchainement_kyc': 'ENCHAINEMENT_KYC_bilan_consommation',
      'image_url': 'https://res.cloudinary.com/dq023imd8/image/upload/v1728468852/conso_7522b1950d.svg',
      'nombre_total_question': 8,
      'pourcentage_progression': 0,
      'temps_minutes': 10,
      'thematique': 'consommation',
    },
    {
      'id_enchainement_kyc': 'ENCHAINEMENT_KYC_bilan_logement',
      'image_url': 'https://res.cloudinary.com/dq023imd8/image/upload/v1728468978/maison_80242d91f3.svg',
      'nombre_total_question': 8,
      'pourcentage_progression': 0,
      'temps_minutes': 9,
      'thematique': 'logement',
    },
  ],
  'pourcentage_completion_totale': 0,
};

const environmentalPerformancePartialData = {
  'bilan_approximatif': {
    'impact_alimentation': 'moyen',
    'impact_consommation': 'fort',
    'impact_logement': null,
    'impact_transport': 'faible',
  },
  'liens_bilans_thematique': [
    {
      'id_enchainement_kyc': 'ENCHAINEMENT_KYC_bilan_transport',
      'image_url': 'https://res.cloudinary.com/dq023imd8/image/upload/v1728466903/Mobilite_df75aefd09.svg',
      'nombre_total_question': 7,
      'pourcentage_progression': 0,
      'temps_minutes': 5,
      'thematique': 'transport',
    },
    {
      'id_enchainement_kyc': 'ENCHAINEMENT_KYC_bilan_alimentation',
      'image_url': 'https://res.cloudinary.com/dq023imd8/image/upload/v1728466523/cuisine_da54797693.svg',
      'nombre_total_question': 5,
      'pourcentage_progression': 20,
      'temps_minutes': 3,
      'thematique': 'alimentation',
    },
    {
      'id_enchainement_kyc': 'ENCHAINEMENT_KYC_bilan_consommation',
      'image_url': 'https://res.cloudinary.com/dq023imd8/image/upload/v1728468852/conso_7522b1950d.svg',
      'nombre_total_question': 8,
      'pourcentage_progression': 0,
      'temps_minutes': 10,
      'thematique': 'consommation',
    },
    {
      'id_enchainement_kyc': 'ENCHAINEMENT_KYC_bilan_logement',
      'image_url': 'https://res.cloudinary.com/dq023imd8/image/upload/v1728468978/maison_80242d91f3.svg',
      'nombre_total_question': 6,
      'pourcentage_progression': 0,
      'temps_minutes': 9,
      'thematique': 'logement',
    },
  ],
  'pourcentage_completion_totale': 23,
};

const environmentalPerformanceFullData = {
  'bilan_complet': {
    'impact_kg_annee': 2930.02701019,
    'impact_thematique': [
      {
        'details': [
          {
            'emoji': '🏛',
            'impact_kg_annee': 1259.4428717769142,
            'label': 'Services publics',
            'pourcentage': null,
            'pourcentage_categorie': 87,
          },
          {
            'emoji': '✉️',
            'impact_kg_annee': 191.4623546094499,
            'label': 'Services marchands',
            'pourcentage': null,
            'pourcentage_categorie': 13,
          },
        ],
        'emoji': '🏛️',
        'impact_kg_annee': 1450.9052263863641,
        'pourcentage': null,
        'thematique': 'services_societaux',
      },
      {
        'details': [
          {
            'emoji': '👕',
            'impact_kg_annee': 486.13999999999993,
            'label': 'Textile',
            'pourcentage': null,
            'pourcentage_categorie': 43,
          },
          {
            'emoji': '🛋️',
            'impact_kg_annee': 139.7448484848485,
            'label': 'Ameublement',
            'pourcentage': null,
            'pourcentage_categorie': 12,
          },
          {
            'emoji': '📦',
            'impact_kg_annee': 123.01123396773932,
            'label': 'Autres produits',
            'pourcentage': null,
            'pourcentage_categorie': 11,
          },
          {
            'emoji': '📺',
            'impact_kg_annee': 120.076661030303,
            'label': 'Numérique',
            'pourcentage': null,
            'pourcentage_categorie': 11,
          },
          {
            'emoji': '🎭',
            'impact_kg_annee': 118.99921707433923,
            'label': 'Loisirs',
            'pourcentage': null,
            'pourcentage_categorie': 11,
          },
          {
            'emoji': '🐶',
            'impact_kg_annee': 53.11748316635982,
            'label': 'Animaux',
            'pourcentage': null,
            'pourcentage_categorie': 5,
          },
          {
            'emoji': '🔌',
            'impact_kg_annee': 51.03181818181818,
            'label': 'Electroménager',
            'pourcentage': null,
            'pourcentage_categorie': 5,
          },
          {'emoji': '🚬', 'impact_kg_annee': 7.28, 'label': 'Tabac', 'pourcentage': null, 'pourcentage_categorie': 1},
        ],
        'emoji': '📦',
        'impact_kg_annee': 1125.4872619054079,
        'pourcentage': null,
        'thematique': 'consommation',
      },
      {
        'details': [
          {
            'emoji': '🚘️',
            'impact_kg_annee': 328.2760868517766,
            'label': 'Voiture',
            'pourcentage': null,
            'pourcentage_categorie': 81,
          },
          {
            'emoji': '🚌',
            'impact_kg_annee': 33.7904763482199,
            'label': 'Transports en commun',
            'pourcentage': null,
            'pourcentage_categorie': 8,
          },
          {
            'emoji': '🛵',
            'impact_kg_annee': 23.196418035061875,
            'label': '2 roues',
            'pourcentage': null,
            'pourcentage_categorie': 6,
          },
          {'emoji': '⛴', 'impact_kg_annee': 11.88805068661542, 'label': 'Ferry', 'pourcentage': null, 'pourcentage_categorie': 3},
          {'emoji': '🚋', 'impact_kg_annee': 8.8198802395209, 'label': 'Train', 'pourcentage': null, 'pourcentage_categorie': 2},
          {'emoji': '✈️', 'impact_kg_annee': 0, 'label': 'Avion', 'pourcentage': null, 'pourcentage_categorie': 0},
          {'emoji': '🚲', 'impact_kg_annee': 0, 'label': 'Mobilité douce', 'pourcentage': null, 'pourcentage_categorie': 0},
          {'emoji': '🏖️', 'impact_kg_annee': 0, 'label': 'Vacances', 'pourcentage': null, 'pourcentage_categorie': 0},
        ],
        'emoji': '🚦',
        'impact_kg_annee': 405.9709121611947,
        'pourcentage': null,
        'thematique': 'transport',
      },
      {
        'details': [
          {
            'emoji': '🏖',
            'impact_kg_annee': 152.08498652513995,
            'label': 'Vacances',
            'pourcentage': null,
            'pourcentage_categorie': 56,
          },
          {
            'emoji': '❄️',
            'impact_kg_annee': 63.176259272727265,
            'label': 'Climatisation',
            'pourcentage': null,
            'pourcentage_categorie': 23,
          },
          {
            'emoji': '🔥',
            'impact_kg_annee': 25.018392992605325,
            'label': 'Chauffage',
            'pourcentage': null,
            'pourcentage_categorie': 9,
          },
          {
            'emoji': '☘️',
            'impact_kg_annee': 21.45057795454545,
            'label': 'Extérieur',
            'pourcentage': null,
            'pourcentage_categorie': 8,
          },
          {
            'emoji': '🧱',
            'impact_kg_annee': 10.680640520949204,
            'label': 'Construction',
            'pourcentage': null,
            'pourcentage_categorie': 4,
          },
          {
            'emoji': '⚡',
            'impact_kg_annee': 0.67071695602011,
            'label': 'Electricité',
            'pourcentage': null,
            'pourcentage_categorie': 0,
          },
          {'emoji': '🏊', 'impact_kg_annee': 0, 'label': 'Piscine', 'pourcentage': null, 'pourcentage_categorie': 0},
        ],
        'emoji': '🏠',
        'impact_kg_annee': 273.0815742219873,
        'pourcentage': null,
        'thematique': 'logement',
      },
      {
        'details': [
          {
            'emoji': '🥦',
            'impact_kg_annee': 657.8000000000001,
            'label': 'Fruits & Légumes',
            'pourcentage': null,
            'pourcentage_categorie': null,
          },
          {
            'emoji': '🥐',
            'impact_kg_annee': 394.20000000000005,
            'label': 'Petit déjeuner',
            'pourcentage': null,
            'pourcentage_categorie': null,
          },
          {
            'emoji': '🥤',
            'impact_kg_annee': 225.37310000000002,
            'label': 'Boissons',
            'pourcentage': null,
            'pourcentage_categorie': null,
          },
          {'emoji': '🥩', 'impact_kg_annee': 0, 'label': 'Viandes', 'pourcentage': null, 'pourcentage_categorie': null},
          {'emoji': '🐟', 'impact_kg_annee': 0, 'label': 'Poissons', 'pourcentage': null, 'pourcentage_categorie': null},
        ],
        'emoji': '🍴',
        'impact_kg_annee': 0,
        'pourcentage': null,
        'thematique': 'alimentation',
      },
    ],
    'top_3': [
      {
        'emoji': '🚘️',
        'impact_kg_annee': 328.2760868517766,
        'label': 'Voiture',
        'pourcentage': null,
        'pourcentage_categorie': 81,
      },
      {'emoji': '✈️', 'impact_kg_annee': 0, 'label': 'Avion', 'pourcentage': null, 'pourcentage_categorie': 0},
      {'emoji': '🛵', 'impact_kg_annee': 23.196418035061875, 'label': '2 roues', 'pourcentage': null, 'pourcentage_categorie': 6},
    ],
  },
  'liens_bilans_thematique': [
    {
      'id_enchainement_kyc': 'ENCHAINEMENT_KYC_bilan_transport',
      'image_url': 'https://res.cloudinary.com/dq023imd8/image/upload/v1728466903/Mobilite_df75aefd09.svg',
      'nombre_total_question': 7,
      'pourcentage_progression': 0,
      'temps_minutes': 5,
      'thematique': 'transport',
    },
    {
      'id_enchainement_kyc': 'ENCHAINEMENT_KYC_bilan_alimentation',
      'image_url': 'https://res.cloudinary.com/dq023imd8/image/upload/v1728466523/cuisine_da54797693.svg',
      'nombre_total_question': 5,
      'pourcentage_progression': 20,
      'temps_minutes': 3,
      'thematique': 'alimentation',
    },
    {
      'id_enchainement_kyc': 'ENCHAINEMENT_KYC_bilan_consommation',
      'image_url': 'https://res.cloudinary.com/dq023imd8/image/upload/v1728468852/conso_7522b1950d.svg',
      'nombre_total_question': 8,
      'pourcentage_progression': 0,
      'temps_minutes': 10,
      'thematique': 'consommation',
    },
    {
      'id_enchainement_kyc': 'ENCHAINEMENT_KYC_bilan_logement',
      'image_url': 'https://res.cloudinary.com/dq023imd8/image/upload/v1728468978/maison_80242d91f3.svg',
      'nombre_total_question': 6,
      'pourcentage_progression': 0,
      'temps_minutes': 9,
      'thematique': 'logement',
    },
  ],
  'pourcentage_completion_totale': 100,
};
