Feature: Action Performance

  Background:
    Given I have actions in my library
      | 'type'  | 'code'                      | 'title'                                              | 'nb_aids_available' |
      | 'bilan' | 'action_bilan_alimentation' | 'Calculer les impacts liés à **votre alimentation**' |                   2 |
    Given I am logged in
    Given The application is launched
    When I tap on the menu button
    Given the API will return
      | 'method' | 'path'                                                                        | 'statusCode' | 'responseData'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
      | 'GET'    | '/utilisateurs/{userId}/actions/bilan/action_bilan_alimentation'              |          200 | {"nombre_actions_en_cours":3,"nombre_actions_faites":3,"nombre_aides_disponibles":0,"code":"action_bilan_alimentation","titre":"Calculer les impacts liés à **votre alimentation**","sous_titre":"Quelques questions pour mieux comprendre vos habitudes et calculer le bilan carbone de votre alimentation","consigne":"Réalisez cette action dans les prochaines semaines et partagez vos retours","label_compteur":"**453 actions** réalisées par la communauté","besoins":[],"comment":null,"pourquoi":null,"type":"bilan","thematique":"alimentation","kycs":[{"code":"KYC_saison_frequence","question":"Faites-vous attention à consommer des fruits et légumes de saison ?","reponse_multiple":[{"code":"jamais","label":"Jamais","selected":true},{"code":"parfois","label":"Parfois","selected":false},{"code":"souvent","label":"Souvent","selected":false},{"code":"toujours","label":"Toujours","selected":false}],"is_answered":true,"categorie":"mission","points":5,"type":"choix_unique","is_NGC":true,"thematique":"alimentation"},{"code":"KYC_gaspillage_alimentaire_frequence","question":"Combien estimez-vous la quantité de déchets alimentaires que vous jetez ?","reponse_multiple":[{"code":"50L","label":"Une poubelle de 50L par semaine","selected":true},{"code":"20L","label":"Une poubelle de 20L par semaine","selected":false},{"code":"peu","label":"Environ une poignée ou l'équivalent d'un bol par semaine","selected":false},{"code":"zero","label":"Zéro","selected":false},{"code":"ne_sais_pas","label":"Je ne sais pas","selected":false}],"is_answered":true,"categorie":"mission","points":5,"type":"choix_unique","is_NGC":true,"thematique":"alimentation"}],"quizzes":[],"aides":[],"services":[],"nom_commune":"Dole","quizz_felicitations":null,"deja_vue":true,"deja_faite":true,"faqs":[],"points":50,"sources":[]} |
      | 'GET'    | '/utilisateurs/{userId}/questionsKYC_v2/KYC_saison_frequence'                 |          200 | {"code":"KYC_saison_frequence","question":"Faites-vous attention à consommer des fruits et légumes de saison ?","reponse_multiple":[{"code":"jamais","label":"Jamais","selected":false},{"code":"parfois","label":"Parfois","selected":false},{"code":"souvent","label":"Souvent","selected":false},{"code":"toujours","label":"Toujours","selected":false}],"is_answered":false,"categorie":"mission","points":5,"type":"choix_unique","is_NGC":true,"thematique":"alimentation"}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
      | "PUT"    | "/utilisateurs/{userId}/questionsKYC_v2/KYC_saison_frequence"                 |          200 | {}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
      | 'GET'    | '/utilisateurs/{userId}/questionsKYC_v2/KYC_gaspillage_alimentaire_frequence' |          200 | {"code":"KYC_gaspillage_alimentaire_frequence","question":"Combien estimez-vous la quantité de déchets alimentaires que vous jetez ?","reponse_multiple":[{"code":"50L","label":"Une poubelle de 50L par semaine","selected":true},{"code":"20L","label":"Une poubelle de 20L par semaine","selected":false},{"code":"peu","label":"Environ une poignée ou l'équivalent d'un bol par semaine","selected":false},{"code":"zero","label":"Zéro","selected":false},{"code":"ne_sais_pas","label":"Je ne sais pas","selected":false}],"is_answered":true,"categorie":"mission","points":5,"type":"choix_unique","is_NGC":true,"thematique":"alimentation"}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
      | "PUT"    | "/utilisateurs/{userId}/questionsKYC_v2/KYC_gaspillage_alimentaire_frequence" |          200 | {}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
      | "GET"    | "/utilisateurs/{userId}/bilans/last_v3/alimentation"                          |          200 | {"thematique":"alimentation","impact_kg_annee":3873.1151821000003,"details":[{"label":"Viandes","impact_kg_annee":2233.296,"emoji":"🥩"},{"label":"Boissons","impact_kg_annee":940.1798000000001,"emoji":"🥤"},{"label":"Poissons","impact_kg_annee":182,"emoji":"🐟"},{"label":"Petit déjeuner","impact_kg_annee":113.15,"emoji":"🥐"},{"label":"Fruits & Légumes","impact_kg_annee":0,"emoji":"🥦"}],"emoji":"🍴"}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
      | "POST"   | "/utilisateurs/{userId}/actions/bilan/action_bilan_alimentation/faite"        |          200 | {}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
    When I tap on {'Actions'}
    When I tap on {'Bilan - Calculer les impacts liés à votre alimentation'}

  Scenario: Voir la première question
    Then I see {'Faites-vous attention à consommer des fruits et légumes de saison ?'}

  Scenario: Répond aux questions
    When I tap on {'Jamais'}
    When I scroll down to {'Question suivante'}
    When I tap on {'Question suivante'}
    Then the API receives
      | 'method' | 'path'                                                        | 'statusCode' | 'requestData'                                                                                                                                                  |
      | "PUT"    | "/utilisateurs/{userId}/questionsKYC_v2/KYC_saison_frequence" |          200 | [{"code": "jamais","selected": true}, {"code": "parfois", "selected": false}, {"code": "souvent", "selected": false}, {"code": "toujours", "selected": false}] |
    When I tap on {'Une poubelle de 50L par semaine'}
    When I scroll down to {'Question suivante'}
    When I tap on {'Question suivante'}
    Then the API receives
      | 'method' | 'path'                                                                        | 'statusCode' | 'requestData'                                                                                                                                                                               |
      | "PUT"    | "/utilisateurs/{userId}/questionsKYC_v2/KYC_gaspillage_alimentaire_frequence" |          200 | [{"code": "50L","selected": true}, {"code": "20L", "selected": false}, {"code": "peu", "selected": false}, {"code": "zero", "selected": false}, {"code": "ne_sais_pas", "selected": false}] |
      | "POST"   | "/utilisateurs/{userId}/actions/bilan/action_bilan_alimentation/faite"        |          200 | null                                                                                                                                                                                        |
    Then I see {'Votre bilan alimentation'}
    Then I see {'Viandes'}

  Scenario: Recommencer le bilan
    When I tap on {'Jamais'}
    When I scroll down to {'Question suivante'}
    When I tap on {'Question suivante'}
    When I tap on {'Une poubelle de 50L par semaine'}
    When I scroll down to {'Question suivante'}
    When I tap on {'Question suivante'}
    Then I see {'Votre bilan alimentation'}
    Then I scroll down to {'Recommmencer le bilan'}
    When I tap on {'Recommmencer le bilan'}
    Then I see {'Question 1 sur 2'}
