Feature: Action Winter

  Background:
    Given I am logged in
    Given the API will return
      | 'method' | 'path'                               | 'statusCode' | 'responseData'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
      | 'GET'    | '/utilisateurs/%7BuserId%7D/actions' |          200 | {"actions":[{"nombre_actions_en_cours":0,"nombre_actions_faites":0,"nombre_aides_disponibles":0,"code":"action_simulateur_winter","titre":"**Faire des économies sur ma facture d’énergie**","type":"simulateur","thematique":"logement","deja_vue":true,"deja_faite":false,"points":30}],"filtres":[{"code":"alimentation","label":"🥦 Alimentation","selected":false},{"code":"transport","label":"🚗 Transports","selected":false},{"code":"logement","label":"🏡 Logement","selected":false},{"code":"consommation","label":"🛒 Consommation durable","selected":false},{"code":"climat","label":"☀️ Environnement","selected":false},{"code":"dechet","label":"🗑️ Déchets","selected":false},{"code":"loisir","label":"⚽ Loisirs","selected":false}],"consultation":"tout","realisation":"tout","nombre_resultats":39,"nombre_resultats_disponibles":39} |
    Given The application is launched
    When I tap on the menu button
    When I tap on {'Actions'}

  Scenario: S'incrire par l'adresse et la connexion est établie
    Given the API will return
      | 'method' | 'path'                                                               | 'statusCode' | 'responseData'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
      | 'GET'    | '/utilisateurs/{userId}/actions/simulateur/action_simulateur_winter' |          200 | {"nombre_actions_en_cours":1,"nombre_actions_faites":1,"nombre_aides_disponibles":0,"code":"action_simulateur_winter","titre":"**Faire des économies sur ma facture d’énergie**","sous_titre":null,"consigne":"Réalisez cette action dans les prochaines semaines et partagez vos retours","label_compteur":"**453 actions** réalisées par la communauté","besoins":[],"comment":null,"pourquoi":"## En quelques mots\n\nObtenez la répartition de votre consommation d'énergie en plus d’actions personnalisées pour réduire votre facture d’électricité sans sacrifier votre confort.","type":"simulateur","thematique":"logement","kycs":[{"code":"KYC_alimentation_achat_vrac","question":"Achetez-vous en vrac ?","reponse_multiple":[{"code":"oui","label":"Oui","selected":false},{"code":"non","label":"Non","selected":true},{"code":"ne_sais_pas","label":"Je ne sais pas","selected":false}],"is_answered":true,"categorie":"test","points":5,"type":"choix_unique","is_NGC":true,"thematique":"alimentation"},{"code":"KYC_appetence_cuisine","question":"Aimez-vous cuisiner ?","reponse_multiple":[{"code":"oui","label":"Oui","selected":false},{"code":"parfois","label":"De temps en temps","selected":false},{"code":"non","label":"Non","selected":false},{"code":"pas_de_reponse","label":"Je ne souhaite pas répondre","selected":false}],"is_answered":false,"categorie":"recommandation","points":5,"type":"choix_unique","is_NGC":false,"thematique":"alimentation"}],"quizzes":[],"aides":[],"services":[],"nom_commune":"Lyon","quizz_felicitations":null,"deja_vue":true,"deja_faite":false,"faqs":[],"points":30,"sources":[],"articles":[],"like_level":null,"enchainement_id":"simulateur_action_simulateur_winter","explications_recommandation":{"liste_explications":[],"est_exclu":false},"explications_recommandation_raw":{"liste_explications":[]}} |
      | 'GET'    | '/utilisateurs/{userId}/logement'                                    |          200 | {"nombre_adultes":2,"nombre_enfants":1,"latitude":47.10341,"longitude":5.480833,"numero_rue":"5","rue":"Chemin de Rougemont","code_postal":"39100","commune":"DOLE","type":"maison","superficie":"superficie_150","proprietaire":null,"chauffage":null,"plus_de_15_ans":true,"dpe":null,"commune_label":"Dole","code_commune":"39198"}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
      | 'POST'   | '/utilisateurs/{userId}/winter/inscription_par_adresse'              |          200 | {}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
    When I tap on {'Faire des économies sur ma facture d’énergie'}
    Then I see {'Réduisez jusqu’à 25% votre facture d’énergie'}
    When I scroll down to {'Commencer'}
    When I tap on {'Commencer'}
    When I enter {'Saudon'} in the {'Nom de famille (du titulaire du contrat électrique)'} field
    When I scroll down to {'Valider'}
    When I tap on {'En activant le suivi de ma consommation, je déclare sur l’honneur être titulaire du compte électrique ou être mandaté par celui-ci. J’autorise Watt Watchers à recueillir mon historique de consommation d’électricité sur 3 ans (demi-heure, journée et puissance maximum quotidienne), ainsi qu’à analyser mes consommations.'}
    When I tap on {'Valider'}
    Then the API receives
      | 'method' | 'path'                                                  | 'statusCode' | 'requestData'                                                                                      |
      | 'POST'   | "/utilisateurs/{userId}/winter/inscription_par_adresse" |          200 | {'nom':'Saudon', 'adresse':'5 Chemin de Rougemont', 'code_postal':'39100', 'code_commune':'39198'} |
    Then I see {'Connexion établie'}

  Scenario: S'incrire par l'adresse et la connexion a échoué
    Given the API will return
      | 'method' | 'path'                                                               | 'statusCode' | 'responseData'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
      | 'GET'    | '/utilisateurs/{userId}/actions/simulateur/action_simulateur_winter' |          200 | {"nombre_actions_en_cours":1,"nombre_actions_faites":1,"nombre_aides_disponibles":0,"code":"action_simulateur_winter","titre":"**Faire des économies sur ma facture d’énergie**","sous_titre":null,"consigne":"Réalisez cette action dans les prochaines semaines et partagez vos retours","label_compteur":"**453 actions** réalisées par la communauté","besoins":[],"comment":null,"pourquoi":"## En quelques mots\n\nObtenez la répartition de votre consommation d'énergie en plus d’actions personnalisées pour réduire votre facture d’électricité sans sacrifier votre confort.","type":"simulateur","thematique":"logement","kycs":[{"code":"KYC_alimentation_achat_vrac","question":"Achetez-vous en vrac ?","reponse_multiple":[{"code":"oui","label":"Oui","selected":false},{"code":"non","label":"Non","selected":true},{"code":"ne_sais_pas","label":"Je ne sais pas","selected":false}],"is_answered":true,"categorie":"test","points":5,"type":"choix_unique","is_NGC":true,"thematique":"alimentation"},{"code":"KYC_appetence_cuisine","question":"Aimez-vous cuisiner ?","reponse_multiple":[{"code":"oui","label":"Oui","selected":false},{"code":"parfois","label":"De temps en temps","selected":false},{"code":"non","label":"Non","selected":false},{"code":"pas_de_reponse","label":"Je ne souhaite pas répondre","selected":false}],"is_answered":false,"categorie":"recommandation","points":5,"type":"choix_unique","is_NGC":false,"thematique":"alimentation"}],"quizzes":[],"aides":[],"services":[],"nom_commune":"Lyon","quizz_felicitations":null,"deja_vue":true,"deja_faite":false,"faqs":[],"points":30,"sources":[],"articles":[],"like_level":null,"enchainement_id":"simulateur_action_simulateur_winter","explications_recommandation":{"liste_explications":[],"est_exclu":false},"explications_recommandation_raw":{"liste_explications":[]}} |
      | 'GET'    | '/utilisateurs/{userId}/logement'                                    |          200 | {"nombre_adultes":2,"nombre_enfants":1,"latitude":47.10341,"longitude":5.480833,"numero_rue":"5","rue":"Chemin de Rougemont","code_postal":"39100","commune":"DOLE","type":"maison","superficie":"superficie_150","proprietaire":null,"chauffage":null,"plus_de_15_ans":true,"dpe":null,"commune_label":"Dole","code_commune":"39198"}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
      | 'POST'   | '/utilisateurs/{userId}/winter/inscription_par_adresse'              |          400 | {}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
    When I tap on {'Faire des économies sur ma facture d’énergie'}
    When I scroll down to {'Commencer'}
    When I tap on {'Commencer'}
    When I enter {'Saudon'} in the {'Nom de famille (du titulaire du contrat électrique)'} field
    When I scroll down to {'Valider'}
    When I tap on {'En activant le suivi de ma consommation, je déclare sur l’honneur être titulaire du compte électrique ou être mandaté par celui-ci. J’autorise Watt Watchers à recueillir mon historique de consommation d’électricité sur 3 ans (demi-heure, journée et puissance maximum quotidienne), ainsi qu’à analyser mes consommations.'}
    When I tap on {'Valider'}
    Then the API receives
      | 'method' | 'path'                                                  | 'statusCode' | 'requestData'                                                                                      |
      | 'POST'   | "/utilisateurs/{userId}/winter/inscription_par_adresse" |          400 | {'nom':'Saudon', 'adresse':'5 Chemin de Rougemont', 'code_postal':'39100', 'code_commune':'39198'} |
    Then I see {'La connexion a échoué'}

  Scenario: S'incrire par le prm et la connexion est établie
    Given the API will return
      | 'method' | 'path'                                                               | 'statusCode' | 'responseData'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
      | 'GET'    | '/utilisateurs/{userId}/actions/simulateur/action_simulateur_winter' |          200 | {"nombre_actions_en_cours":1,"nombre_actions_faites":1,"nombre_aides_disponibles":0,"code":"action_simulateur_winter","titre":"**Faire des économies sur ma facture d’énergie**","sous_titre":null,"consigne":"Réalisez cette action dans les prochaines semaines et partagez vos retours","label_compteur":"**453 actions** réalisées par la communauté","besoins":[],"comment":null,"pourquoi":"## En quelques mots\n\nObtenez la répartition de votre consommation d'énergie en plus d’actions personnalisées pour réduire votre facture d’électricité sans sacrifier votre confort.","type":"simulateur","thematique":"logement","kycs":[{"code":"KYC_alimentation_achat_vrac","question":"Achetez-vous en vrac ?","reponse_multiple":[{"code":"oui","label":"Oui","selected":false},{"code":"non","label":"Non","selected":true},{"code":"ne_sais_pas","label":"Je ne sais pas","selected":false}],"is_answered":true,"categorie":"test","points":5,"type":"choix_unique","is_NGC":true,"thematique":"alimentation"},{"code":"KYC_appetence_cuisine","question":"Aimez-vous cuisiner ?","reponse_multiple":[{"code":"oui","label":"Oui","selected":false},{"code":"parfois","label":"De temps en temps","selected":false},{"code":"non","label":"Non","selected":false},{"code":"pas_de_reponse","label":"Je ne souhaite pas répondre","selected":false}],"is_answered":false,"categorie":"recommandation","points":5,"type":"choix_unique","is_NGC":false,"thematique":"alimentation"}],"quizzes":[],"aides":[],"services":[],"nom_commune":"Lyon","quizz_felicitations":null,"deja_vue":true,"deja_faite":false,"faqs":[],"points":30,"sources":[],"articles":[],"like_level":null,"enchainement_id":"simulateur_action_simulateur_winter","explications_recommandation":{"liste_explications":[],"est_exclu":false},"explications_recommandation_raw":{"liste_explications":[]}} |
      | 'GET'    | '/utilisateurs/{userId}/logement'                                    |          200 | {"nombre_adultes":2,"nombre_enfants":1,"latitude":47.10341,"longitude":5.480833,"numero_rue":"5","rue":"Chemin de Rougemont","code_postal":"39100","commune":"DOLE","type":"maison","superficie":"superficie_150","proprietaire":null,"chauffage":null,"plus_de_15_ans":true,"dpe":null,"commune_label":"Dole","code_commune":"39198"}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
      | 'POST'   | '/utilisateurs/{userId}/winter/inscription_par_prm'                  |          200 | {}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
    When I tap on {'Faire des économies sur ma facture d’énergie'}
    Then I see {'Réduisez jusqu’à 25% votre facture d’énergie'}
    When I scroll down to {'Commencer'}
    When I tap on {'Commencer'}
    When I tap on {'Avec mon numéro de PRM'}
    When I enter {'21209261841110'} in the {'Numéro de PRM'} field
    When I enter {'Saudon'} in the {'Nom de famille (du titulaire du contrat électrique)'} field
    When I scroll down to {'Valider'}
    When I tap on {'En activant le suivi de ma consommation, je déclare sur l’honneur être titulaire du compte électrique ou être mandaté par celui-ci. J’autorise Watt Watchers à recueillir mon historique de consommation d’électricité sur 3 ans (demi-heure, journée et puissance maximum quotidienne), ainsi qu’à analyser mes consommations.'}
    When I tap on {'Valider'}
    Then the API receives
      | 'method' | 'path'                                              | 'statusCode' | 'requestData'                            |
      | 'POST'   | "/utilisateurs/{userId}/winter/inscription_par_prm" |          200 | {'nom':'Saudon', 'prm':'21209261841110'} |
    Then I see {'Connexion établie'}

  Scenario: Après que la connexion a échoué, modifier un champ de relancer pas la popup
    Given the API will return
      | 'method' | 'path'                                                               | 'statusCode' | 'responseData'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
      | 'GET'    | '/utilisateurs/{userId}/actions/simulateur/action_simulateur_winter' |          200 | {"nombre_actions_en_cours":1,"nombre_actions_faites":1,"nombre_aides_disponibles":0,"code":"action_simulateur_winter","titre":"**Faire des économies sur ma facture d’énergie**","sous_titre":null,"consigne":"Réalisez cette action dans les prochaines semaines et partagez vos retours","label_compteur":"**453 actions** réalisées par la communauté","besoins":[],"comment":null,"pourquoi":"## En quelques mots\n\nObtenez la répartition de votre consommation d'énergie en plus d’actions personnalisées pour réduire votre facture d’électricité sans sacrifier votre confort.","type":"simulateur","thematique":"logement","kycs":[{"code":"KYC_alimentation_achat_vrac","question":"Achetez-vous en vrac ?","reponse_multiple":[{"code":"oui","label":"Oui","selected":false},{"code":"non","label":"Non","selected":true},{"code":"ne_sais_pas","label":"Je ne sais pas","selected":false}],"is_answered":true,"categorie":"test","points":5,"type":"choix_unique","is_NGC":true,"thematique":"alimentation"},{"code":"KYC_appetence_cuisine","question":"Aimez-vous cuisiner ?","reponse_multiple":[{"code":"oui","label":"Oui","selected":false},{"code":"parfois","label":"De temps en temps","selected":false},{"code":"non","label":"Non","selected":false},{"code":"pas_de_reponse","label":"Je ne souhaite pas répondre","selected":false}],"is_answered":false,"categorie":"recommandation","points":5,"type":"choix_unique","is_NGC":false,"thematique":"alimentation"}],"quizzes":[],"aides":[],"services":[],"nom_commune":"Lyon","quizz_felicitations":null,"deja_vue":true,"deja_faite":false,"faqs":[],"points":30,"sources":[],"articles":[],"like_level":null,"enchainement_id":"simulateur_action_simulateur_winter","explications_recommandation":{"liste_explications":[],"est_exclu":false},"explications_recommandation_raw":{"liste_explications":[]}} |
      | 'GET'    | '/utilisateurs/{userId}/logement'                                    |          200 | {"nombre_adultes":2,"nombre_enfants":1,"latitude":47.10341,"longitude":5.480833,"numero_rue":"5","rue":"Chemin de Rougemont","code_postal":"39100","commune":"DOLE","type":"maison","superficie":"superficie_150","proprietaire":null,"chauffage":null,"plus_de_15_ans":true,"dpe":null,"commune_label":"Dole","code_commune":"39198"}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
      | 'POST'   | '/utilisateurs/{userId}/winter/inscription_par_adresse'              |          400 | {}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
    When I tap on {'Faire des économies sur ma facture d’énergie'}
    When I scroll down to {'Commencer'}
    When I tap on {'Commencer'}
    When I enter {'Saudon'} in the {'Nom de famille (du titulaire du contrat électrique)'} field
    When I scroll down to {'Valider'}
    When I tap on {'En activant le suivi de ma consommation, je déclare sur l’honneur être titulaire du compte électrique ou être mandaté par celui-ci. J’autorise Watt Watchers à recueillir mon historique de consommation d’électricité sur 3 ans (demi-heure, journée et puissance maximum quotidienne), ainsi qu’à analyser mes consommations.'}
    When I tap on {'Valider'}
    When I tap on {'Retour'}
    When I tap on {'En activant le suivi de ma consommation, je déclare sur l’honneur être titulaire du compte électrique ou être mandaté par celui-ci. J’autorise Watt Watchers à recueillir mon historique de consommation d’électricité sur 3 ans (demi-heure, journée et puissance maximum quotidienne), ainsi qu’à analyser mes consommations.'}
    Then I don't see {'La connexion a échoué'}

  Scenario: Après que la connexion a échoué, renseigner le numéro de PRM change le formulaire
    Given the API will return
      | 'method' | 'path'                                                               | 'statusCode' | 'responseData'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
      | 'GET'    | '/utilisateurs/{userId}/actions/simulateur/action_simulateur_winter' |          200 | {"nombre_actions_en_cours":1,"nombre_actions_faites":1,"nombre_aides_disponibles":0,"code":"action_simulateur_winter","titre":"**Faire des économies sur ma facture d’énergie**","sous_titre":null,"consigne":"Réalisez cette action dans les prochaines semaines et partagez vos retours","label_compteur":"**453 actions** réalisées par la communauté","besoins":[],"comment":null,"pourquoi":"## En quelques mots\n\nObtenez la répartition de votre consommation d'énergie en plus d’actions personnalisées pour réduire votre facture d’électricité sans sacrifier votre confort.","type":"simulateur","thematique":"logement","kycs":[{"code":"KYC_alimentation_achat_vrac","question":"Achetez-vous en vrac ?","reponse_multiple":[{"code":"oui","label":"Oui","selected":false},{"code":"non","label":"Non","selected":true},{"code":"ne_sais_pas","label":"Je ne sais pas","selected":false}],"is_answered":true,"categorie":"test","points":5,"type":"choix_unique","is_NGC":true,"thematique":"alimentation"},{"code":"KYC_appetence_cuisine","question":"Aimez-vous cuisiner ?","reponse_multiple":[{"code":"oui","label":"Oui","selected":false},{"code":"parfois","label":"De temps en temps","selected":false},{"code":"non","label":"Non","selected":false},{"code":"pas_de_reponse","label":"Je ne souhaite pas répondre","selected":false}],"is_answered":false,"categorie":"recommandation","points":5,"type":"choix_unique","is_NGC":false,"thematique":"alimentation"}],"quizzes":[],"aides":[],"services":[],"nom_commune":"Lyon","quizz_felicitations":null,"deja_vue":true,"deja_faite":false,"faqs":[],"points":30,"sources":[],"articles":[],"like_level":null,"enchainement_id":"simulateur_action_simulateur_winter","explications_recommandation":{"liste_explications":[],"est_exclu":false},"explications_recommandation_raw":{"liste_explications":[]}} |
      | 'GET'    | '/utilisateurs/{userId}/logement'                                    |          200 | {"nombre_adultes":2,"nombre_enfants":1,"latitude":47.10341,"longitude":5.480833,"numero_rue":"5","rue":"Chemin de Rougemont","code_postal":"39100","commune":"DOLE","type":"maison","superficie":"superficie_150","proprietaire":null,"chauffage":null,"plus_de_15_ans":true,"dpe":null,"commune_label":"Dole","code_commune":"39198"}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
      | 'POST'   | '/utilisateurs/{userId}/winter/inscription_par_adresse'              |          400 | {}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
    When I tap on {'Faire des économies sur ma facture d’énergie'}
    When I scroll down to {'Commencer'}
    When I tap on {'Commencer'}
    When I enter {'Saudon'} in the {'Nom de famille (du titulaire du contrat électrique)'} field
    When I scroll down to {'Valider'}
    When I tap on {'En activant le suivi de ma consommation, je déclare sur l’honneur être titulaire du compte électrique ou être mandaté par celui-ci. J’autorise Watt Watchers à recueillir mon historique de consommation d’électricité sur 3 ans (demi-heure, journée et puissance maximum quotidienne), ainsi qu’à analyser mes consommations.'}
    When I tap on {'Valider'}
    When I tap on {'Renseigner le numéro de PRM'}
    Then I see {'Numéro de PRM'}
