Feature: Action MAIF

  Background:
    Given I am logged in
    Given the API will return
      | 'method' | 'path'                               | 'statusCode' | 'responseData'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
      | 'GET'    | '/utilisateurs/%7BuserId%7D/actions' |          200 | {"actions":[{"nombre_actions_en_cours":0,"nombre_actions_faites":0,"nombre_aides_disponibles":0,"code":"action_simulateur_maif","emoji":"🌧️","titre":"Connaître les risques naturels auxquels votre logement est exposé","type":"simulateur","thematique":"logement","deja_vue":true,"deja_faite":false,"points":30}],"filtres":[{"code":"alimentation","label":"🥦 Alimentation","selected":false},{"code":"transport","label":"🚗 Transports","selected":false},{"code":"logement","label":"🏡 Logement","selected":false},{"code":"consommation","label":"🛒 Consommation durable","selected":false},{"code":"climat","label":"☀️ Environnement","selected":false},{"code":"dechet","label":"🗑️ Déchets","selected":false},{"code":"loisir","label":"⚽ Loisirs","selected":false}],"consultation":"tout","realisation":"tout","nombre_resultats":39,"nombre_resultats_disponibles":39} |
    Given The application is launched
    When I tap on the menu button
    When I tap on {'Actions'}

  Scenario: Voir le simulateur avec uniquement la commune renseignée
    Given the API will return
      | 'method' | 'path'                                                             | 'statusCode' | 'responseData'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
      | 'GET'    | '/utilisateurs/{userId}/actions/simulateur/action_simulateur_maif' |          200 | {"nombre_actions_en_cours":3,"nombre_actions_faites":3,"nombre_aides_disponibles":1,"code":"action_simulateur_maif","emoji":"🌧️","titre":"Connaître les risques naturels auxquels votre logement est exposé","label_compteur":"**453 simulations** réalisées par la communauté","besoins":[],"comment":"","pourquoi":"## En **quelques mots**\n\nChaque année, des milliers de logements subissent des sinistres liés à des aléas naturels.\n\nEn consultant les risques (inondations, mouvements de terrain, feux de forêt…), vous pouvez adapter vos travaux, souscrire une assurance adaptée et éviter des dégâts coûteux.","type":"simulateur","thematique":"logement","quizzes":[],"aides":[],"services":[],"nom_commune":"Dole","quizz_felicitations":null,"deja_vue":true,"deja_faite":false,"faqs":[],"points":30,"sources":[],"articles":[],"enchainement_id":"","explications_recommandation":{"liste_explications":[],"est_exclu":false},"explications_recommandation_raw":{"liste_explications":[]}} |
      | 'GET'    | '/utilisateurs/{userId}/logement'                                  |          200 | {"nombre_adultes":2,"nombre_enfants":1,"code_postal":"39100","commune":"Dole","type":"maison","superficie":"superficie_150","proprietaire":null,"chauffage":null,"plus_de_15_ans":true,"dpe":null,"commune_label":"Dole","code_commune":"39198"}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
      | 'GET'    | '/utilisateurs/%7BuserId%7D/risques_commune?code_commune=39198'    |          200 | {"code_commune":"39198","nom_commune":"Dole","nombre_catastrophes_naturels":13,"pourcentage_commune_risque_inondation":21,"pourcentage_commune_risque_secheresse_geotechnique":100}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
    When I tap on {'🌧️ Connaître les risques naturels auxquels votre logement est exposé'}
    Then I don't see {'Vos risques'}
    Then I see {'Les chiffres clés de Dole'}
    Then I see {'21%'}
    Then I see {'100%'}

  Scenario: Voir le simulateur avec une adresse complète
    Given the API will return
      | 'method' | 'path'                                                                            | 'statusCode' | 'requestData' | 'responseData'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
      | 'GET'    | '/utilisateurs/{userId}/actions/simulateur/action_simulateur_maif'                |          200 | null          | {"nombre_actions_en_cours":3,"nombre_actions_faites":3,"nombre_aides_disponibles":1,"code":"action_simulateur_maif","emoji":"🌧️","titre":"Connaître les risques naturels auxquels votre logement est exposé","label_compteur":"**453 simulations** réalisées par la communauté","besoins":[],"comment":"","pourquoi":"## En **quelques mots**\n\nChaque année, des milliers de logements subissent des sinistres liés à des aléas naturels.\n\nEn consultant les risques (inondations, mouvements de terrain, feux de forêt…), vous pouvez adapter vos travaux, souscrire une assurance adaptée et éviter des dégâts coûteux.","type":"simulateur","thematique":"logement","quizzes":[],"aides":[],"services":[],"nom_commune":"Dole","quizz_felicitations":null,"deja_vue":true,"deja_faite":false,"faqs":[],"points":30,"sources":[],"articles":[],"enchainement_id":"","explications_recommandation":{"liste_explications":[],"est_exclu":false},"explications_recommandation_raw":{"liste_explications":[]}} |
      | 'POST'   | "/utilisateurs/{userId}/actions/simulateur/action_simulateur_maif/faite"          |          200 | null          | {}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
      | 'GET'    | '/utilisateurs/{userId}/logement'                                                 |          200 | null          | {"nombre_adultes":2,"nombre_enfants":1,"latitude":47.10341,"longitude":5.480833,"numero_rue":"5","rue":"Chemin de Rougemont","code_postal":"39100","commune":"Dole","type":"maison","superficie":"superficie_150","proprietaire":null,"chauffage":null,"plus_de_15_ans":true,"dpe":null,"commune_label":"Dole","code_commune":"39198"}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
      | 'GET'    | '/utilisateurs/%7BuserId%7D/risques_commune?code_commune=39198'                   |          200 | null          | {"code_commune":"39198","nom_commune":"Dole","nombre_catastrophes_naturels":13,"pourcentage_commune_risque_inondation":21,"pourcentage_commune_risque_secheresse_geotechnique":100}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
      | 'GET'    | '/utilisateurs/%7BuserId%7D/risques_adresse?latitude=47.10341&longitude=5.480833' |          200 | null          | [{"type_risque":"secheresse","niveau_risque":"fort","titre":"Risques de sécheresse"},{"type_risque":"seisme","niveau_risque":"faible","titre":"Risques sismiques"},{"type_risque":"inondation","niveau_risque":"tres_faible","titre":"Risques d'inondations"},{"type_risque":"radon","niveau_risque":"faible","titre":"Risques d'exposition au radon"},{"type_risque":"submersion","niveau_risque":"tres_faible","titre":"Risques de submersion"},{"type_risque":"tempete","niveau_risque":"tres_faible","titre":"Risques de tempêtes"},{"type_risque":"argile","niveau_risque":"moyen","titre":"Risques retrait-gonflement des sols argileux"}]                                                                                                                                                                                                                                                                                                                                                                 |
    When I tap on {'🌧️ Connaître les risques naturels auxquels votre logement est exposé'}
    Then I see {'5 Chemin de Rougemont 39100 Dole'}
    Then I don't see {'Choisir comme adresse principale'}
    Then I see {'Vos risques'}
    Then I see {'Risques de sécheresse'}
    Then I don't see {"Risques d'inondations"}
    Then I see {'Risques retrait-gonflement des sols argileux'}
    Then I see {'Risques sismiques'}
    Then I see {"Risques d'exposition au radon"}
    Then the API receive
      | 'method' | 'path'                                                                   | 'statusCode' | 'requestData' |
      | 'POST'   | "/utilisateurs/{userId}/actions/simulateur/action_simulateur_maif/faite" |          200 | null          |

  Scenario: Modifier l'adresse sans la définir comme adresse principale
    Given the API will return
      | 'method' | 'path'                                                                            | 'statusCode' | 'requestData' | 'responseData'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
      | 'GET'    | '/utilisateurs/{userId}/actions/simulateur/action_simulateur_maif'                |          200 | null          | {"nombre_actions_en_cours":3,"nombre_actions_faites":3,"nombre_aides_disponibles":1,"code":"action_simulateur_maif","emoji":"🌧️","titre":"Connaître les risques naturels auxquels votre logement est exposé","label_compteur":"**453 simulations** réalisées par la communauté","besoins":[],"comment":"","pourquoi":"## En **quelques mots**\n\nChaque année, des milliers de logements subissent des sinistres liés à des aléas naturels.\n\nEn consultant les risques (inondations, mouvements de terrain, feux de forêt…), vous pouvez adapter vos travaux, souscrire une assurance adaptée et éviter des dégâts coûteux.","type":"simulateur","thematique":"logement","quizzes":[],"aides":[],"services":[],"nom_commune":"Dole","quizz_felicitations":null,"deja_vue":true,"deja_faite":false,"faqs":[],"points":30,"sources":[],"articles":[],"enchainement_id":"","explications_recommandation":{"liste_explications":[],"est_exclu":false},"explications_recommandation_raw":{"liste_explications":[]}} |
      | 'GET'    | '/utilisateurs/{userId}/logement'                                                 |          200 | null          | {"nombre_adultes":2,"nombre_enfants":1,"latitude":47.10341,"longitude":5.480833,"numero_voie":"5","nom_voie":"Chemin de Rougemont","code_postal":"39100","commune":"Dole","type":"maison","superficie":"superficie_150","proprietaire":null,"chauffage":null,"plus_de_15_ans":true,"dpe":null,"commune_label":"Dole","code_commune":"39198"}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | 'GET'    | '/utilisateurs/%7BuserId%7D/risques_commune?code_commune=39198'                   |          200 | null          | {"code_commune":"39198","nom_commune":"Dole","nombre_catastrophes_naturels":13,"pourcentage_commune_risque_inondation":21,"pourcentage_commune_risque_secheresse_geotechnique":100}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
      | 'GET'    | '/utilisateurs/%7BuserId%7D/risques_adresse?latitude=47.10341&longitude=5.480833' |          200 | null          | [{"type_risque":"secheresse","niveau_risque":"fort","titre":"Risques de sécheresse"},{"type_risque":"seisme","niveau_risque":"faible","titre":"Risques sismiques"},{"type_risque":"inondation","niveau_risque":"tres_faible","titre":"Risques d'inondations"},{"type_risque":"radon","niveau_risque":"faible","titre":"Risques d'exposition au radon"},{"type_risque":"submersion","niveau_risque":"tres_faible","titre":"Risques de submersion"},{"type_risque":"tempete","niveau_risque":"tres_faible","titre":"Risques de tempêtes"},{"type_risque":"argile","niveau_risque":"moyen","titre":"Risques retrait-gonflement des sols argileux"}]                                                                                                                                                                                                                                                                                                                                                                 |
    When I tap on {'🌧️ Connaître les risques naturels auxquels votre logement est exposé'}
    When I scroll down to {'Choisissez une adresse'}
    When I enter {"110 Rue Garibaldi"} in the autocomplete field
    Given the API will return
      | 'method' | 'path'                                                                             | 'statusCode' | 'requestData' | 'responseData'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
      | 'GET'    | '/utilisateurs/%7BuserId%7D/risques_adresse?latitude=45.766368&longitude=4.850666' |          200 | null          | [{"type_risque":"secheresse","niveau_risque":"faible","titre":"Risques de sécheresse"},{"type_risque":"seisme","niveau_risque":"faible","titre":"Risques sismiques"},{"type_risque":"inondation","niveau_risque":"moyen","titre":"Risques d'inondations"},{"type_risque":"radon","niveau_risque":"faible","titre":"Risques d'exposition au radon"},{"type_risque":"submersion","niveau_risque":"tres_faible","titre":"Risques de submersion"},{"type_risque":"tempete","niveau_risque":"tres_faible","titre":"Risques de tempêtes"},{"type_risque":"argile","niveau_risque":"faible","titre":"Risques retrait-gonflement des sols argileux"}] |
      | 'GET'    | '/utilisateurs/%7BuserId%7D/risques_commune?code_commune=69386'                    |          200 | null          | {"code_commune":"69386","nom_commune":"Lyon 6e Arrondissement","nombre_catastrophes_naturels":20,"pourcentage_commune_risque_inondation":35,"pourcentage_commune_risque_secheresse_geotechnique":21}                                                                                                                                                                                                                                                                                                                                                                                                                                          |
    When I tap on {'110 Rue Garibaldi 69006 Lyon'}
    Then I see {'Les chiffres clés de Lyon'}

  Scenario: Modifier l'adresse comme adresse principale
    Given the API will return
      | 'method' | 'path'                                                                            | 'statusCode' | 'requestData' | 'responseData'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
      | 'GET'    | '/utilisateurs/{userId}/actions/simulateur/action_simulateur_maif'                |          200 | null          | {"nombre_actions_en_cours":3,"nombre_actions_faites":3,"nombre_aides_disponibles":1,"code":"action_simulateur_maif","emoji":"🌧️","titre":"Connaître les risques naturels auxquels votre logement est exposé","label_compteur":"**453 simulations** réalisées par la communauté","besoins":[],"comment":"","pourquoi":"## En **quelques mots**\n\nChaque année, des milliers de logements subissent des sinistres liés à des aléas naturels.\n\nEn consultant les risques (inondations, mouvements de terrain, feux de forêt…), vous pouvez adapter vos travaux, souscrire une assurance adaptée et éviter des dégâts coûteux.","type":"simulateur","thematique":"logement","quizzes":[],"aides":[],"services":[],"nom_commune":"Dole","quizz_felicitations":null,"deja_vue":true,"deja_faite":false,"faqs":[],"points":30,"sources":[],"articles":[],"enchainement_id":"","explications_recommandation":{"liste_explications":[],"est_exclu":false},"explications_recommandation_raw":{"liste_explications":[]}} |
      | 'POST'   | "/utilisateurs/{userId}/actions/simulateur/action_simulateur_maif/faite"          |          200 | null          | {}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
      | 'GET'    | '/utilisateurs/{userId}/logement'                                                 |          200 | null          | {"nombre_adultes":2,"nombre_enfants":1,"latitude":47.10341,"longitude":5.480833,"numero_voie":"5","nom_voie":"Chemin de Rougemont","code_postal":"39100","commune":"Dole","type":"maison","superficie":"superficie_150","proprietaire":null,"chauffage":null,"plus_de_15_ans":true,"dpe":null,"commune_label":"Dole","code_commune":"39198"}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | 'GET'    | '/utilisateurs/%7BuserId%7D/risques_commune?code_commune=39198'                   |          200 | null          | {"code_commune":"39198","nom_commune":"Dole","nombre_catastrophes_naturels":13,"pourcentage_commune_risque_inondation":21,"pourcentage_commune_risque_secheresse_geotechnique":100}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
      | 'GET'    | '/utilisateurs/%7BuserId%7D/risques_adresse?latitude=47.10341&longitude=5.480833' |          200 | null          | [{"type_risque":"secheresse","niveau_risque":"fort","titre":"Risques de sécheresse"},{"type_risque":"seisme","niveau_risque":"faible","titre":"Risques sismiques"},{"type_risque":"inondation","niveau_risque":"tres_faible","titre":"Risques d'inondations"},{"type_risque":"radon","niveau_risque":"faible","titre":"Risques d'exposition au radon"},{"type_risque":"submersion","niveau_risque":"tres_faible","titre":"Risques de submersion"},{"type_risque":"tempete","niveau_risque":"tres_faible","titre":"Risques de tempêtes"},{"type_risque":"argile","niveau_risque":"moyen","titre":"Risques retrait-gonflement des sols argileux"}]                                                                                                                                                                                                                                                                                                                                                                 |
    When I tap on {'🌧️ Connaître les risques naturels auxquels votre logement est exposé'}
    When I scroll down to {'Choisissez une adresse'}
    When I enter {"110 Rue Garibaldi"} in the autocomplete field
    Given the API will return
      | 'method' | 'path'                                                                             | 'statusCode' | 'requestData' | 'responseData'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
      | 'GET'    | '/utilisateurs/%7BuserId%7D/risques_adresse?latitude=45.766368&longitude=4.850666' |          200 | null          | [{"type_risque":"secheresse","niveau_risque":"faible","titre":"Risques de sécheresse"},{"type_risque":"seisme","niveau_risque":"faible","titre":"Risques sismiques"},{"type_risque":"inondation","niveau_risque":"moyen","titre":"Risques d'inondations"},{"type_risque":"radon","niveau_risque":"faible","titre":"Risques d'exposition au radon"},{"type_risque":"submersion","niveau_risque":"tres_faible","titre":"Risques de submersion"},{"type_risque":"tempete","niveau_risque":"tres_faible","titre":"Risques de tempêtes"},{"type_risque":"argile","niveau_risque":"faible","titre":"Risques retrait-gonflement des sols argileux"}] |
      | 'GET'    | '/utilisateurs/%7BuserId%7D/risques_commune?code_commune=69386'                    |          200 | null          | {"code_commune":"69386","nom_commune":"Lyon 6e Arrondissement","nombre_catastrophes_naturels":20,"pourcentage_commune_risque_inondation":35,"pourcentage_commune_risque_secheresse_geotechnique":21}                                                                                                                                                                                                                                                                                                                                                                                                                                          |
      | 'PATCH'  | '/utilisateurs/{userId}/logement'                                                  |          200 | null          | {}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
    When I tap on {'110 Rue Garibaldi 69006 Lyon'}
    When I tap on {'Enregistrer'}
    Then I don't see {'Enregistrer'}
    Then the API receive
      | 'method' | 'path'                                                                   | 'statusCode' | 'requestData'                                                                                                                     |
      | 'POST'   | "/utilisateurs/{userId}/actions/simulateur/action_simulateur_maif/faite" |          200 | null                                                                                                                              |
      | 'PATCH'  | "/utilisateurs/{userId}/logement"                                        |          200 | {"rue":"Rue Garibaldi","numero_rue":"110","code_postal":"69006","code_commune":"69386","latitude":45.766368,"longitude":4.850666} |
