Feature: Action Performance

  Background:
    Given I have actions in my library
      | 'type'  | 'code'                      | 'title'                                              | 'nb_aids_available' |
      | 'bilan' | 'action_bilan_alimentation' | 'Calculer les impacts liés à **votre alimentation**' |                   2 |
    Given I am logged in
    Given The application is launched
    When I tap on the menu button

  Scenario: Voir la première question
    Given the API will return
      | 'method' | 'path'                                                           | 'statusCode' | 'responseData'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
      | 'GET'    | '/utilisateurs/{userId}/actions/bilan/action_bilan_alimentation' |          200 | {"nombre_actions_en_cours":2,"nombre_actions_faites":2,"nombre_aides_disponibles":0,"code":"action_bilan_alimentation","titre":"Calculer les impacts liés à **votre alimentation**","sous_titre":"Quelques questions pour mieux comprendre vos habitudes et calculer le bilan carbone de votre alimentation","consigne":"Réalisez cette action dans les prochaines semaines et partagez vos retours","label_compteur":"**453 actions** réalisées par la communauté","besoins":[],"comment":null,"pourquoi":null,"type":"bilan","thematique":"alimentation","kycs":[{"code":"KYC_saison_frequence","question":"Faites-vous attention à consommer des fruits et légumes de saison ?","reponse_multiple":[{"code":"jamais","label":"Jamais","selected":false},{"code":"parfois","label":"Parfois","selected":false},{"code":"souvent","label":"Souvent","selected":false},{"code":"toujours","label":"Toujours","selected":false}],"is_answered":false,"categorie":"mission","points":5,"type":"choix_unique","is_NGC":true,"thematique":"alimentation"}],"quizzes":[],"aides":[],"services":[],"nom_commune":"Dole","quizz_felicitations":null,"deja_vue":false,"deja_faite":false,"faqs":[],"points":50,"sources":[]} |
      | 'GET'    | '/utilisateurs/{userId}/questionsKYC_v2/KYC_saison_frequence'    |          200 | {"code":"KYC_saison_frequence","question":"Faites-vous attention à consommer des fruits et légumes de saison ?","reponse_multiple":[{"code":"jamais","label":"Jamais","selected":false},{"code":"parfois","label":"Parfois","selected":false},{"code":"souvent","label":"Souvent","selected":false},{"code":"toujours","label":"Toujours","selected":false}],"is_answered":false,"categorie":"mission","points":5,"type":"choix_unique","is_NGC":true,"thematique":"alimentation"}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
    When I tap on {'Actions'}
    When I tap on {'Calculer les impacts liés à votre alimentation'}
    Then I see {'Faites-vous attention à consommer des fruits et légumes de saison ?'}
