Feature: Action Performance

  Background:
    Given I have actions in my library
      | 'type'  | 'code'                      | 'title'                                              | 'nb_aids_available' |
      | 'bilan' | 'action_bilan_alimentation' | 'Calculer les impacts liés à **votre alimentation**' |                   2 |
    Given I am logged in
    Given the API will return
      | 'method' | 'path'                                                                                                                 | 'statusCode' | 'responseData'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
      | 'GET'    | '/utilisateurs/{userId}/actions/bilan/action_bilan_alimentation'                                                       |          200 | {"nombre_actions_en_cours":0,"nombre_actions_faites":0,"nombre_aides_disponibles":0,"code":"action_bilan_alimentation","titre":"Calculer les impacts liés à **votre alimentation**","sous_titre":"Quelques questions pour mieux comprendre vos habitudes et calculer le bilan carbone de votre alimentation","consigne":"Réalisez cette action dans les prochaines semaines et partagez vos retours","label_compteur":"**453 actions** réalisées par la communauté","besoins":[],"comment":null,"pourquoi":null,"type":"bilan","thematique":"alimentation","quizzes":[],"aides":[],"services":[],"nom_commune":"Bordeaux","quizz_felicitations":null,"deja_vue":true,"deja_faite":false,"faqs":[],"points":50,"sources":[],"articles":[],"like_level":null,"enchainement_id":"bilan_action_bilan_alimentation","explications_recommandation":{"liste_explications":[],"est_exclu":false},"explications_recommandation_raw":{"liste_explications":[]}} |
      | 'GET'    | '/utilisateurs/{userId}/enchainementQuestionsKYC_v2/bilan_action_bilan_alimentation/first'                             |          200 | {"nombre_total_questions":2,"nombre_total_questions_effectives":2,"position_courante":1,"question_courante":{"code":"KYC_alimentation_regime","question":"Quel est votre régime alimentaire habituel","reponse_multiple":[{"code":"chaque_jour_viande","label":"Viande chaque jour","selected":false},{"code":"peu_viande","label":"Peu de viande","selected":false},{"code":"vegetarien","label":"Végétarien","selected":false},{"code":"vegetalien","label":"Végétalien","selected":false}],"is_answered":false,"categorie":"mission","points":5,"type":"choix_unique","is_NGC":false,"thematique":"alimentation"},"is_first":true,"is_last":false,"is_out_of_range":false}                                                                                                                                                                                                                                                                         |
      | 'GET'    | '/utilisateurs/{userId}/questionsKYC_v2/KYC_alimentation_regime'                                                       |          200 | {"code":"KYC_alimentation_regime","question":"Quel est votre régime alimentaire habituel","reponse_multiple":[{"code":"chaque_jour_viande","label":"Viande chaque jour","selected":false},{"code":"peu_viande","label":"Peu de viande","selected":false},{"code":"vegetarien","label":"Végétarien","selected":false},{"code":"vegetalien","label":"Végétalien","selected":false}],"is_answered":false,"categorie":"mission","points":5,"type":"choix_unique","is_NGC":false,"thematique":"alimentation"}                                                                                                                                                                                                                                                                                                                                                                                                                                              |
      | 'PUT'    | '/utilisateurs/{userId}/questionsKYC_v2/KYC_alimentation_regime'                                                       |          200 | {}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
      | 'GET'    | '/utilisateurs/{userId}/enchainementQuestionsKYC_v2/bilan_action_bilan_alimentation/following/KYC_alimentation_regime' |          200 | {"nombre_total_questions":2,"nombre_total_questions_effectives":2,"position_courante":2,"question_courante":{"code":"KYC_petitdej","question":"Quel petit déjeuner vous correspond le plus ?","reponse_multiple":[{"code":"pain","label":" Viennoiserie et pain","selected":false},{"code":"lait","label":"Lait et céréales","selected":false},{"code":"bacon","label":"Salé (type britannique, bacon et oeuf)","selected":false},{"code":"fruit","label":"Fruits","selected":false},{"code":"aucun","label":"Pas de petit-dej'","selected":false}],"is_answered":false,"categorie":"mission","points":5,"type":"choix_unique","is_NGC":true,"thematique":"alimentation"},"is_first":false,"is_last":false,"is_out_of_range":false}                                                                                                                                                                                                                   |
      | 'GET'    | '/utilisateurs/{userId}/questionsKYC_v2/KYC_petitdej'                                                                  |          200 | {"code":"KYC_petitdej","question":"Quel petit déjeuner vous correspond le plus ?","reponse_multiple":[{"code":"pain","label":" Viennoiserie et pain","selected":false},{"code":"lait","label":"Lait et céréales","selected":false},{"code":"bacon","label":"Salé (type britannique, bacon et oeuf)","selected":false},{"code":"fruit","label":"Fruits","selected":false},{"code":"aucun","label":"Pas de petit-dej'","selected":false}],"is_answered":false,"categorie":"mission","points":5,"type":"choix_unique","is_NGC":true,"thematique":"alimentation"}                                                                                                                                                                                                                                                                                                                                                                                         |
      | 'PUT'    | '/utilisateurs/{userId}/questionsKYC_v2/KYC_petitdej'                                                                  |          200 | {}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
      | 'GET'    | '/utilisateurs/{userId}/enchainementQuestionsKYC_v2/bilan_action_bilan_alimentation/following/KYC_petitdej'            |          200 | {"nombre_total_questions":2,"nombre_total_questions_effectives":2,"position_courante":-1,"is_first":false,"is_last":false,"is_out_of_range":false}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
      | "POST"   | "/utilisateurs/{userId}/actions/bilan/action_bilan_alimentation/faite"                                                 |          200 | {}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
      | "GET"    | "/utilisateurs/{userId}/bilans/last_v3/alimentation"                                                                   |          200 | {"thematique":"alimentation","impact_kg_annee":3873.1151821000003,"details":[{"label":"Viandes","impact_kg_annee":2233.296,"emoji":"🥩"},{"label":"Boissons","impact_kg_annee":940.1798000000001,"emoji":"🥤"},{"label":"Poissons","impact_kg_annee":182,"emoji":"🐟"},{"label":"Petit déjeuner","impact_kg_annee":113.15,"emoji":"🥐"},{"label":"Fruits & Légumes","impact_kg_annee":0,"emoji":"🥦"}],"emoji":"🍴"}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
    Given The application is launched
    When I tap on the menu button
    When I tap on {'Actions'}
    When I tap on {'Calculer les impacts liés à votre alimentation'}

  Scenario: Voir la première question
    Then I see {'Quel est votre régime alimentaire habituel'}

  Scenario: Répond aux questions
    When I tap on {'Peu de viande'}
    When I scroll down to {'Question suivante'}
    When I tap on {'Question suivante'}
    Then the API receives
      | 'method' | 'path'                                                           | 'statusCode' | 'requestData'                                                                                                                                                                       |
      | 'PUT'    | '/utilisateurs/{userId}/questionsKYC_v2/KYC_alimentation_regime' |          200 | [{"code": "chaque_jour_viande", "selected": false}, {"code": "peu_viande", "selected": true}, {"code": "vegetarien", "selected": false}, {"code": "vegetalien", "selected": false}] |
    When I scroll down to {'Viennoiserie et pain'}
    When I tap on {'Viennoiserie et pain'}
    When I scroll down to {'Question suivante'}
    When I tap on {'Question suivante'}
    Then the API receives
      | 'method' | 'path'                                                                 | 'statusCode' | 'requestData'                                                                                                                                                            |
      | 'PUT'    | "/utilisateurs/{userId}/questionsKYC_v2/KYC_petitdej"                  |          200 | [{"code":"pain","selected":true},{"code":"lait","selected":false},{"code":"bacon","selected":false},{"code":"fruit","selected":false},{"code":"aucun","selected":false}] |
      | 'POST'   | "/utilisateurs/{userId}/actions/bilan/action_bilan_alimentation/faite" |          200 | null                                                                                                                                                                     |
    Then I see {'Votre bilan alimentation'}
    Then I see {'Viandes'}

  Scenario: Recommencer le bilan
    When I tap on {'Peu de viande'}
    When I scroll down to {'Question suivante'}
    When I tap on {'Question suivante'}
    When I scroll down to {'Viennoiserie et pain'}
    When I tap on {'Viennoiserie et pain'}
    When I scroll down to {'Question suivante'}
    When I tap on {'Question suivante'}
    Then I see {'Votre bilan alimentation'}
    Then I scroll down to {'Recommmencer le bilan'}
    When I tap on {'Recommmencer le bilan'}
    Then I see {'Question 1 sur 2'}
