Feature: KYC edit

  Background:
    Given I am logged in
    Given the API will return
      | 'method' | 'path'                                                    | 'statusCode' | 'responseData'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
      | 'GET'    | '/utilisateurs/{userId}/questionsKYC_v2'                  |          200 | [{"code":"MOSAIC_CHAUFFAGE","question":"Quels modes de chauffage existent chez vous ?","reponse_multiple":[{"code":"KYC_chauffage_bois","label":"Bois","emoji":"🪵","image_url":"https://res.cloudinary.com/dq023imd8/image/upload/v1726497242/Screenshot_2024_09_16_at_16_22_55_4fcb2d1a5b.png","selected":true},{"code":"KYC_chauffage_fioul","label":"Fioul","emoji":"🛢️","image_url":"https://res.cloudinary.com/dq023imd8/image/upload/v1726497260/Screenshot_2024_09_16_at_16_23_05_4103677680.png","selected":false},{"code":"KYC_chauffage_gaz","label":"Gaz","emoji":"🏭","image_url":"https://res.cloudinary.com/dq023imd8/image/upload/v1726497275/Screenshot_2024_09_16_at_16_23_19_1084c4bd18.png","selected":false},{"code":"KYC_chauffage_elec","label":"Électricité","emoji":"⚡️","image_url":"https://res.cloudinary.com/dq023imd8/image/upload/v1727275914/Screenshot_2024_09_25_at_16_51_08_876426bef9.png","selected":false}],"is_answered":true,"categorie":"mission","points":5,"type":"mosaic_boolean","is_NGC":false,"thematique":"logement"}] |
      | 'GET'    | '/utilisateurs/{userId}/questionsKYC_v2/MOSAIC_CHAUFFAGE' |          200 | {"code":"MOSAIC_CHAUFFAGE","question":"Quels modes de chauffage existent chez vous ?","reponse_multiple":[{"code":"KYC_chauffage_bois","label":"Bois","emoji":"🪵","image_url":"https://res.cloudinary.com/dq023imd8/image/upload/v1726497242/Screenshot_2024_09_16_at_16_22_55_4fcb2d1a5b.png","selected":true},{"code":"KYC_chauffage_fioul","label":"Fioul","emoji":"🛢️","image_url":"https://res.cloudinary.com/dq023imd8/image/upload/v1726497260/Screenshot_2024_09_16_at_16_23_05_4103677680.png","selected":false},{"code":"KYC_chauffage_gaz","label":"Gaz","emoji":"🏭","image_url":"https://res.cloudinary.com/dq023imd8/image/upload/v1726497275/Screenshot_2024_09_16_at_16_23_19_1084c4bd18.png","selected":false},{"code":"KYC_chauffage_elec","label":"Électricité","emoji":"⚡️","image_url":"https://res.cloudinary.com/dq023imd8/image/upload/v1727275914/Screenshot_2024_09_25_at_16_51_08_876426bef9.png","selected":false}],"is_answered":true,"categorie":"mission","points":5,"type":"mosaic_boolean","is_NGC":false,"thematique":"logement"}   |
      | "PUT"    | '/utilisateurs/{userId}/questionsKYC_v2/MOSAIC_CHAUFFAGE' |          200 | {}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
    Given The application is launched
    When I tap on the menu button
    When I tap on {'Mon profil'}
    When I tap on {'Mes réponses'}

  Scenario: Question mosaique Répondre aucune de ces propostions
    When I tap on {'Quels modes de chauffage existent chez vous ?'}
    When I scroll down to {'Aucune de ces propositions'}
    When I tap on {'Aucune de ces propositions'}
    Then the API receive
      | 'method' | 'path'                                                    | 'statusCode' | 'requestData'                                                                                                                                                                                 |
      | "PUT"    | '/utilisateurs/{userId}/questionsKYC_v2/MOSAIC_CHAUFFAGE' |          200 | [{"code":"KYC_chauffage_bois","selected":false},{"code":"KYC_chauffage_fioul","selected":false},{"code":"KYC_chauffage_gaz","selected":false},{"code":"KYC_chauffage_elec","selected":false}] |
