Feature: Longue vie aux objets

  Background:
    Given I am logged in
    Given the API will return
      | 'method' | 'path'                                                                   | 'statusCode' | 'responseData'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
      | 'GET'    | '/utilisateurs/{userId}/thematiques/consommation'                        |          200 | {"thematique":"consommation","est_personnalisation_necessaire":false,"enchainement_questions_personnalisation":"ENCHAINEMENT_KYC_personnalisation_consommation","liste_actions_recommandees":[{"nombre_actions_en_cours":0,"nombre_actions_faites":0,"nombre_aides_disponibles":0,"code":"action_stoppub","titre":"**Afficher un Stop Pub** sur votre boîte aux lettres","sous_titre":null,"type":"classique","thematique":"consommation","deja_vue":false,"deja_faite":false,"points":100}],"nombre_actions":6,"nombre_aides":2,"nombre_simulateurs":0,"nom_commune":"Lyon 6e Arrondissement"}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
      | 'GET'    | '/utilisateurs/{userId}/thematiques/consommation/recherche_services'     |          200 | [{"id_service":"longue_vie_objets","titre":"Que faire de mes objets ?","sous_titre":"donner, réparer, recycler,...","external_url":"https://longuevieauxobjets.ademe.fr/","icon_url":"https://agir-front-dev.osc-fr1.scalingo.io/commerce.webp","univers":"consommation","thematique":"consommation","is_available_inhouse":true},{"id_service":"reparerabilite","titre":"Mon appareil se répare-t-il facilement ?","sous_titre":"Epargnons nos ressources","external_url":"https://epargnonsnosressources.gouv.fr/indice-de-reparabilite/","icon_url":"https://epargnonsnosressources.gouv.fr/wp-content/uploads/2023/09/picto_reparabilite_desktop-115.png","univers":"consommation","thematique":"consommation","is_available_inhouse":false},{"id_service":"labels","titre":"Se repérer dans les labels","sous_titre":"Epargnons nos ressources","external_url":"https://epargnonsnosressources.gouv.fr/labels-environnementaux/","icon_url":"https://epargnonsnosressources.gouv.fr/wp-content/uploads/2023/09/outils_index-des-labels_icon_desktop_115x95.png","univers":"consommation","thematique":"consommation","is_available_inhouse":false},{"id_service":"diagnostiquer","titre":"Diagnostiquer une panne","sous_titre":"Epargnons nos ressources","external_url":"https://epargnonsnosressources.gouv.fr/diagnostic-pannes-appareils/","icon_url":"https://epargnonsnosressources.gouv.fr/wp-content/uploads/2023/10/icons-outils_diagnostique.png","univers":"consommation","thematique":"consommation","is_available_inhouse":false},{"id_service":"reparer","titre":"Tutos pour réparer mes objets","sous_titre":"Epargnons nos ressources","external_url":"https://epargnonsnosressources.gouv.fr/tutos-reparation/","icon_url":"https://epargnonsnosressources.gouv.fr/wp-content/uploads/2023/09/picto_tutoreparation_desktop_115x95.png","univers":"consommation","thematique":"consommation","is_available_inhouse":false}] |
      | 'GET'    | '/utilisateurs/{userId}/recherche_services/longue_vie_objets/categories' |          200 | [{"code":"vos_objets","label":"Vos objets","is_default":true},{"code":"donner","label":"Donner","is_default":false},{"code":"reparer","label":"Réparer","is_default":false},{"code":"vendre","label":"Vendre","is_default":false},{"code":"louer","label":"Louer","is_default":false},{"code":"acheter","label":"Acheter d'occasion","is_default":false},{"code":"emprunter","label":"Emprunter","is_default":false}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
      | 'POST'   | '/utilisateurs/{userId}/recherche_services/longue_vie_objets/search2'    |          200 | {"encore_plus_resultats_dispo":true,"resultats":[{"id":"refashion_TLC-REFASHION-PAV-3289828","titre":"EBS LE RELAIS NORD PAS DE CALAIS","adresse_rue":"2 rue Anatole France, 69006, Lyon 6e  Arrondissement","est_favoris":false,"nombre_favoris":0,"distance_metres":67,"categories":["donner"],"latitude":45.772192,"longitude":4.856551,"ingredients":[],"etapes_recette":[],"categories_labels":["Donner"],"sources":["Longue Vie Aux Objets","ADEME","REFASHION"]}]}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
    Given The application is launched
    When I tap on {1} text {'👕 Mes achats'}
    When I tap on {'🔧 Des adresses de réparateur près de chez vous'}

  Scenario: Voir les suggestions
    Then I see {"EBS LE RELAIS NORD PAS DE CALAIS"}
    Then the API receives
      | 'method' | 'path'                                                                | 'statusCode' | 'requestData'                                                                |
      | 'POST'   | "/utilisateurs/{userId}/recherche_services/longue_vie_objets/search2" |          200 | {"categorie": "vos_objets", "nombre_max_resultats": 9, "rayon_metres": 5000} |

  Scenario: Choisir une catégorie
    When I tap on {'Vos objets'}
    When I tap on {'Donner'}
    Then I see {"EBS LE RELAIS NORD PAS DE CALAIS"}
    Then the API receives
      | 'method' | 'path'                                                                | 'statusCode' | 'requestData'                                                            |
      | 'POST'   | "/utilisateurs/{userId}/recherche_services/longue_vie_objets/search2" |          200 | {"categorie": "donner", "nombre_max_resultats": 9, "rayon_metres": 5000} |

  Scenario: Recherche avec une adresse
    When I enter {"110 Rue Garibaldi"} in the autocomplete field
    When I tap on {'110 Rue Garibaldi 69006 Lyon'}
    Then I see {"EBS LE RELAIS NORD PAS DE CALAIS"}
    Then the API receives
      | 'method' | 'path'                                                                | 'statusCode' | 'requestData'                                                                                                     |
      | 'POST'   | "/utilisateurs/{userId}/recherche_services/longue_vie_objets/search2" |          200 | {"categorie":"vos_objets","nombre_max_resultats":9,"rayon_metres":5000,"latitude":45.766368,"longitude":4.850666} |

  Scenario: Aller sur la page de détails
    Given the API will return
      | 'method' | 'path'                                                                                                         | 'statusCode' | 'responseData'                                                                                                                                                                                                                                                                                                                                                                                                         |
      | 'GET'    | '/utilisateurs/{userId}/recherche_services/longue_vie_objets/last_results/refashion_TLC-REFASHION-PAV-3289828' |          200 | {"id":"refashion_TLC-REFASHION-PAV-3289828","titre":"EBS LE RELAIS NORD PAS DE CALAIS","adresse_rue":"2 rue Anatole France, 69006, Lyon 6e  Arrondissement","est_favoris":false,"nombre_favoris":0,"distance_metres":67,"categories":["donner"],"latitude":45.772192,"longitude":4.856551,"ingredients":[],"etapes_recette":[],"categories_labels":["Donner"],"sources":["Longue Vie Aux Objets","ADEME","REFASHION"]} |
    When I tap on {'EBS LE RELAIS NORD PAS DE CALAIS'}
    When I scroll down to {'Sources :'}
    Then I see {'· REFASHION'}
