Feature: Recipe

  Background:
    Given I am logged in
    Given The application is launched

  Scenario: See recipe detail
    Given I have actions in my library
      | 'type'      | 'code' | 'title'                                        | 'nb_aids_available' |
      | 'classique' | '3'    | 'Tester une **nouvelle recette végétarienne**' |                   1 |
    Given I have action detail in my library
      | 'id' | 'title'                                        | 'subTitle'                                                                                                    | 'how'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | 'why'                                                                                                                                                                                                                                                                                                                   | 'service_id' | 'service_category' |
      | '3'  | 'Tester une **nouvelle recette végétarienne**' | 'Faites des économies et le plein de vitamines ! Cette semaine, on cuisine une recette saine et délicieuse !' | '# Nos astuces\n\n- **Revisitez vos classiques** : Lasagnes au légumes, chili sin carne, re-découvrez vos plats favoris en version végétariennes \n\n- **Protéines végétales** : Associez légumineuses (lentilles, pois chiches) et céréales (riz, quinoa) pour un plat complet.\n\n- **Variez les textures** : Alternez croquant (graines, noix) et fondant (avocats, patates douces)\n\n- **Épices et herbes** : Boostez les saveurs avec du curry, paprika fumé, curcuma, cumin ou herbes fraîches.' | '# En quelques mots\n\n- Les repas à base de légumes sont en moyenne **30% moins chers** que ceux à base de viande.\n\n- Les nutriments contenus dans les légumes de saison sont une grande aide pour passer l’hiver !\n\n![test alt](https://agir-cms-prod.osc-secnum-fr1.scalingo.io/admin/70674f63fc3904c20de0.svg)' | 'recettes'   | 'vegan'            |
    When I tap on the menu button
    When I tap on {'Actions'}
    Given I have recipe services in my library
    Given I have recipe detail in my library
      | 'id' | 'title'                                  | 'preparation_time' |
      | '1'  | 'Salade de pâtes complètes et lentilles' |                  5 |
    When I tap on {'Tester une nouvelle recette végétarienne'}
    When I scroll down to {'Salade de pâtes complètes et lentilles'}
    When I tap on {'Salade de pâtes complètes et lentilles'}
    Then I see {'Temps de préparation : 5 min'}
    Then I see {'© Santé publique France'}

  Scenario: See recipes
    Given the API will return
      | 'method' | 'path'                                                                                                    | 'statusCode' | 'responseData'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
      | 'GET'    | '/utilisateurs/%7BuserId%7D/aides_v2?thematique=alimentation'                                             |          200 | {"couverture_aides_ok":false,"liste_aides":[]}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
      | 'GET'    | '/utilisateurs/{userId}/enchainementQuestionsKYC_v2/ENCHAINEMENT_KYC_personnalisation_alimentation/first' |          200 | {"nombre_total_questions":4,"nombre_total_questions_effectives":4,"position_courante":3,"question_courante":{"code":"MOSAIC_REDUCTION_DECHETS","question":"Quels éco-gestes mettez-vous en place pour réduire vos déchets ?","reponse_multiple":[{"code":"KYC_alimentation_compostage","label":"Compostage biodéchets","emoji":null,"image_url":"https://res.cloudinary.com/dq023imd8/image/upload/v1728749522/482602_8af4f622d9.png","selected":false},{"code":"KYC_alimentation_reduc_gaspi_alim","label":"Réduire gaspillage alimentaire","emoji":null,"image_url":"https://res.cloudinary.com/dq023imd8/image/upload/v1728749522/482602_8af4f622d9.png","selected":false},{"code":"KYC_alimentation_stoppub","label":"Stop pub","emoji":null,"image_url":"https://res.cloudinary.com/dq023imd8/image/upload/v1728749522/482602_8af4f622d9.png","selected":true},{"code":"KYC_alimentation_achat_vrac","label":"Achat en vrac","emoji":null,"image_url":"https://res.cloudinary.com/dq023imd8/image/upload/v1728749522/482602_8af4f622d9.png","selected":false}],"is_answered":true,"categorie":"mission","points":5,"type":"mosaic_boolean","is_NGC":false,"thematique":"dechet"},"is_first":false,"is_last":false,"is_out_of_range":false} |
    When I tap on {1} text {'🍛 Me nourrir'}
    Then I see {'Les recettes de septembre'}
