Feature: Aides dans les thématiques

  Background:
    Given I am logged in
    Given The application is launched

  Scenario: Voir les aides
    Given the API will return
      | 'method' | 'path'                                                                                                | 'statusCode' | 'responseData'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
      | 'GET'    | '/utilisateurs/{userId}/thematiques/logement'                                                         |          200 | {"thematique":"logement","est_personnalisation_necessaire":true,"enchainement_questions_personnalisation":"ENCHAINEMENT_KYC_personnalisation_logement","liste_actions_recommandees":[],"nombre_actions":27,"nombre_aides":6,"nombre_simulateurs":0,"nom_commune":"Villette-d'Anthon","est_utilisateur_ngc":false}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
      | 'GET'    | '/utilisateurs/%7BuserId%7D/aides_v2?thematique=logement'                                             |          200 | {"couverture_aides_ok":false,"liste_aides":[{"content_id":"9","titre":"Être accompagné par France Rénov pour votre rénovation énergétique","contenu":"<h1>Contenu</h1>","derniere_maj":"2025-06-16T00:00:00.000Z","url_simulateur":null,"url_source":"https://france-renov.gouv.fr/preparer-projet/trouver-conseiller","url_demande":"https://france-renov.gouv.fr/preparer-projet/trouver-conseiller","is_simulateur":false,"codes_postaux":[],"thematiques":["logement"],"thematiques_label":["🏡 Logement"],"montant_max":null,"besoin_desc":"Rénover son logement","besoin":"reno_logement","clicked_demande":false,"clicked_infos":false,"partenaire_nom":"Gouvernement Français","partenaire_url":null,"partenaire_logo_url":"https://res.cloudinary.com/dq023imd8/image/upload/t_media_lib_thumb/v1739369270/logo_vectoriel_republique_francaise_afb2d8ca57.jpg","echelle":"National","est_gratuit":true,"deja_vue_le":"2025-07-07T14:59:17.175Z"}]} |
      | 'GET'    | '/utilisateurs/{userId}/enchainementQuestionsKYC_v2/ENCHAINEMENT_KYC_personnalisation_logement/first' |          200 | {"nombre_total_questions":5,"nombre_total_questions_effectives":5,"position_courante":1,"question_courante":{"code":"KYC_type_logement","question":"Dans quel type de logement vivez-vous ?","reponse_multiple":[{"code":"type_maison","label":"Maison","selected":false},{"code":"type_appartement","label":"Appartement","selected":false}],"is_answered":false,"is_skipped":false,"categorie":"recommandation","points":5,"type":"choix_unique","is_NGC":true,"thematique":"logement"},"is_first":true,"is_last":false,"is_out_of_range":false}                                                                                                                                                                                                                                                                                                                                                                                                         |
    When I tap on {1} text {'🏠 Me loger'}
    Then I scroll down to {'Mes aides'}
    Then I see {'Mes aides'}
    Then I see {'Être accompagné par France Rénov pour votre rénovation énergétique'}

  Scenario: Ne pas voir la section Aides si aucune aide
    Given the API will return
      | 'method' | 'path'                                                                                                | 'statusCode' | 'responseData'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | 'GET'    | '/utilisateurs/{userId}/thematiques/logement'                                                         |          200 | {"thematique":"logement","est_personnalisation_necessaire":true,"enchainement_questions_personnalisation":"ENCHAINEMENT_KYC_personnalisation_logement","liste_actions_recommandees":[],"nombre_actions":27,"nombre_aides":6,"nombre_simulateurs":0,"nom_commune":"Villette-d'Anthon","est_utilisateur_ngc":false}                                                                                                                                                                                                                                  |
      | 'GET'    | '/utilisateurs/%7BuserId%7D/aides_v2?thematique=logement'                                             |          200 | {"couverture_aides_ok":false,"liste_aides":[]}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | 'GET'    | '/utilisateurs/{userId}/enchainementQuestionsKYC_v2/ENCHAINEMENT_KYC_personnalisation_logement/first' |          200 | {"nombre_total_questions":5,"nombre_total_questions_effectives":5,"position_courante":1,"question_courante":{"code":"KYC_type_logement","question":"Dans quel type de logement vivez-vous ?","reponse_multiple":[{"code":"type_maison","label":"Maison","selected":false},{"code":"type_appartement","label":"Appartement","selected":false}],"is_answered":false,"is_skipped":false,"categorie":"recommandation","points":5,"type":"choix_unique","is_NGC":true,"thematique":"logement"},"is_first":true,"is_last":false,"is_out_of_range":false} |
    When I tap on {1} text {'🏠 Me loger'}
    Then I don't see {'Mes aides'}
