abstract final class AssetImages {
  const AssetImages._();

  static const actions = 'assets/images/actions.webp';
  static const actionsRecommandedEmpty = 'assets/images/actions_recommanded_empty.webp';
  static const ademe = 'assets/images/logo_ademe.svg';
  static const ademeSemantic = 'Logo de l’ADEME : Agence de la transition écologique';
  static const alimentation = 'assets/images/alimentation.svg';
  static const badgeIcon = 'assets/images/badge_icon.svg';
  static const badgePionner = 'assets/images/badge_pioneer.webp';
  static const bibliothequeEmpty = 'assets/images/bibliotheque_illustration.svg';
  static const consommation = 'assets/images/consommation.svg';
  static const errorIllustration = 'assets/images/error_illustration.svg';
  static const feedback = 'assets/images/feedback.webp';
  static const flags = 'assets/images/flags.svg';
  static const franceConnect = 'assets/images/france_connect.svg';
  static const franceNationVerte = 'assets/images/logo_fnv.png';
  static const franceNationVerteSemantic = 'Logo de France Nation Verte';
  static const homeIllustration = 'assets/images/home_illustration.webp';
  static const illustration1 = 'assets/images/illustration1.svg';
  static const illustration2 = 'assets/images/illustration2.svg';
  static const illustration3 = 'assets/images/illustration3.svg';
  static const illustration4 = 'assets/images/illustration4.svg';
  static const illustration5 = 'assets/images/illustration5.svg';
  static const impactCo2Illustration = 'assets/images/service-fruits.webp';
  static const impactCo2Logo = 'assets/images/logo_impact_co2.svg';
  static const leaf = 'assets/images/leaf.svg';
  static const logement = 'assets/images/logement.svg';
  static const lvaoStore = 'assets/images/lvao_store.svg';
  static const mangerBouger = 'assets/images/manger_bouger.webp';
  static const mangerBougerLogo = 'assets/images/logo_manger_bouger.svg';
  static const mesAidesVeloLogo = 'assets/images/mesaidesvelo_logo.svg';
  static const mesAidesVeloTexte = 'assets/images/mesaidesvelo_texte.svg';
  static const nosGestesClimat = 'assets/images/nos_gestes_climat.png';
  static const nosGestesClimatIllustration = 'assets/images/bilan-carbone-ngc-screenshot.svg';
  static const presDeChezVousStore = 'assets/images/pres_de_chez_vous_store.svg';
  static const republiqueFrancaise = 'assets/images/logo_rf.svg';
  static const republiqueFrancaiseSemantic = 'Logo officiel de la République Française';
  static const resetPointsIllustrations1 = 'assets/images/reset_points_1.webp';
  static const resetPointsIllustrations2 = 'assets/images/reset_points_2.webp';
  static const transport = 'assets/images/transport.svg';
}
